name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: npm ci && npm run alfredPackage
      - name: Upload workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: alfred-dft200.alfredworkflow
          path: alfred-dft200.alfredworkflow
